  name: Deploy to Uberspace
  uses: easingthemes/ssh-deploy@v5.1.0
  env:
    SSH_PRIVATE_KEY: ${{ secrets.UBERSPACE_SSH_KEY }}
    ARGS: "-avz --delete"
    SOURCE: "site/"
    REMOTE_HOST: "michel.uber.space"
    REMOTE_USER: "michel"
    TARGET: "/home/michel/html/"
